spring:
  application:
    name: ai-doc-processing-server-webmvc-mcp

  ai:
    mcp:
      server:
        name: ai-doc-processing-server-webmvc-mcp
        version: 1.0.0
        type: SYNC
        instructions: "Document Processing AI Server"
        sse-endpoint: /api/v1/sse
        sse-message-endpoint: /api/v1/messages
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
    openai:
      api-key: "" # Set in your environment
      embedding:
        model: text-embedding-ada-002
    vector-store:
        type: QDRANT
        uri: http://localhost:6333
        enabled: true
        qdrant:
          api-key: "" # Set in your environment
        collection-name: document_embeddings
logging:
    level:
      io.modelcontextprotocol: TRACE
      org.springframework.ai.mcp: TRACE

